### ISSUE TITLE
[1.18.2] Tag error

### ISSUE THREAD

**Issue by drakray** [Nyancatpig/Alexs-Abnormalities-1.18.2#2]
```
Couldn't load tag minecraft:walls as it is missing following references: alexsabnormalities:bone_serpent_tooth_wall
```
causes cascading error which make pickaxe not working

**Comment by drakray** [comment]
also `alexsabnormalities:shark_tooth_wall` and `alexsabnormalities:cachalot_whale_tooth_wall`

**Comment by Nyancatpig** [comment]
Thankyou for informing me
This issue will be fixed in the latest update
